- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - networking-l2gw-tempest-dummy
    gate:
      jobs:
        - networking-l2gw-tempest-dummy

- job:
    name: networking-l2gw-tempest-dummy
    description: |
      Run Tempest tests from the networking-l2gw Tempest plugin with a dummy plugin
    parent: devstack-tempest
    required-projects:
      - openstack/networking-l2gw
      - openstack/networking-l2gw-tempest-plugin
      - openstack/neutron-tempest-plugin
    vars:
      tempest_test_regex: networking_l2gw_tempest_plugin
      tox_envlist: all
      devstack_localrc:
        NETWORKING_L2GW_SERVICE_DRIVER: L2GW:l2gw:networking_l2gw.services.l2gateway.service_drivers.L2gwDriver:default
        TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin /opt/stack/networking-l2gw-tempest-plugin"'
        USE_PYTHON3: True
      devstack_plugins:
        networking-l2gw: https://opendev.org/openstack/networking-l2gw
      devstack_services:
        l2gw-plugin: true
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
